# Name of workflow
name: My Test Workflow

# Define the trigger event(s)
on: [push]

# Jobs run in parallel by defect, each runs steps in sequence
jobs:

    # Job to print something to the screen
    say-hello: 
        runs-on: ubuntu-22.04
        steps: 
          - run: echo "Hello, Github Actions!"
    
    # Job to build and test our C program
    build-and-test:
      needs: [say-hello]
      runs-on: ubuntu-22.04
      steps:
          # Uses github.com/actiions/checkout
          - name: Checkout this repo
            uses: actions/checkout@v3
          
          # Install dependencies
          - name: Install dependencies
            run: sudo apt-get install -y python3 build-essential
          
          # See where you are in the WM
          - run: pwd

          # Run our test
          - name: Run Test
            run: python3 test.py 



