# Name of workflow
name: My Test Workflow

# Define the trigger event(s)
on: [push]

# Jobs run in parallel by defect, each runs steps in sequence
jobs:

    # Job to print something to the screen
    say-hello: 
        runs-on: ubuntu-22.04
        steps: 
          - run: echo "Hello, Github Actions!"
          